openapi: 3.0.0
info:
  title: Better-Auth Signup and Signin API
  description: API contracts for authentication and background profiling in the Humanoid Robotics Book
  version: 1.0.0
servers:
  - url: https://humanoid-robotics-book.com/api
    description: Production server
  - url: https://staging.humanoid-robotics-book.com/api
    description: Staging server

paths:
  /auth/signup:
    post:
      summary: Register a new user with background profiling
      description: Creates a new user account with email, password, and background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - softwareBackground
                - hardwareBackground
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "user@example.com"
                password:
                  type: string
                  minLength: 8
                  description: User's password (minimum 8 characters)
                  example: "SecurePassword123"
                softwareBackground:
                  type: object
                  description: User's software background information
                  properties:
                    programmingLanguages:
                      type: array
                      items:
                        type: string
                      description: Programming languages the user knows
                      example: ["JavaScript", "Python", "C++"]
                    frameworks:
                      type: array
                      items:
                        type: string
                      description: Frameworks the user has experience with
                      example: ["React", "Node.js", "ROS"]
                    experienceLevel:
                      type: string
                      enum: ["beginner", "intermediate", "advanced"]
                      description: Overall software experience level
                      example: "intermediate"
                hardwareBackground:
                  type: object
                  description: User's hardware background information
                  properties:
                    roboticsKits:
                      type: array
                      items:
                        type: string
                      description: Robotics kits the user has experience with
                      example: ["Arduino", "Raspberry Pi", "NVIDIA Jetson"]
                    sensors:
                      type: array
                      items:
                        type: string
                      description: Sensors the user has worked with
                      example: ["IMU", "LIDAR", "Camera"]
                    actuators:
                      type: array
                      items:
                        type: string
                      description: Actuators the user has experience with
                      example: ["Servos", "Stepper Motors", "DC Motors"]
                    experienceLevel:
                      type: string
                      enum: ["beginner", "intermediate", "advanced"]
                      description: Overall hardware experience level
                      example: "beginner"
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "User registered successfully"
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/signin:
    post:
      summary: Authenticate a user
      description: Authenticates a user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "user@example.com"
                password:
                  type: string
                  description: User's password
                  example: "SecurePassword123"
      responses:
        '200':
          description: User successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "User authenticated successfully"
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/profile:
    get:
      summary: Get authenticated user profile
      description: Retrieves the profile of the currently authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update user profile
      description: Updates the authenticated user's profile, including background information
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                softwareBackground:
                  $ref: '#/components/schemas/SoftwareBackground'
                hardwareBackground:
                  $ref: '#/components/schemas/HardwareBackground'
      responses:
        '200':
          description: User profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "Profile updated successfully"
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/signout:
    post:
      summary: Sign out user
      description: Ends the current user session
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User signed out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User signed out successfully"
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
          example: "user_123456789"
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        createdAt:
          type: string
          format: date-time
          description: When the user account was created
          example: "2023-01-01T00:00:00Z"
        lastSignInAt:
          type: string
          format: date-time
          description: When the user last signed in
          example: "2023-01-02T10:30:00Z"
        softwareBackground:
          $ref: '#/components/schemas/SoftwareBackground'
        hardwareBackground:
          $ref: '#/components/schemas/HardwareBackground'
        backgroundComplete:
          type: boolean
          description: Whether the user has completed background profiling
          example: true

    SoftwareBackground:
      type: object
      properties:
        programmingLanguages:
          type: array
          items:
            type: string
          description: Programming languages the user knows
          example: ["JavaScript", "Python", "C++"]
        frameworks:
          type: array
          items:
            type: string
          description: Frameworks the user has experience with
          example: ["React", "Node.js", "ROS"]
        experienceLevel:
          type: string
          enum: ["beginner", "intermediate", "advanced"]
          description: Overall software experience level
          example: "intermediate"

    HardwareBackground:
      type: object
      properties:
        roboticsKits:
          type: array
          items:
            type: string
          description: Robotics kits the user has experience with
          example: ["Arduino", "Raspberry Pi", "NVIDIA Jetson"]
        sensors:
          type: array
          items:
            type: string
          description: Sensors the user has worked with
          example: ["IMU", "LIDAR", "Camera"]
        actuators:
          type: array
          items:
            type: string
          description: Actuators the user has experience with
          example: ["Servos", "Stepper Motors", "DC Motors"]
        experienceLevel:
          type: string
          enum: ["beginner", "intermediate", "advanced"]
          description: Overall hardware experience level
          example: "beginner"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
          example: "Invalid credentials"
        message:
          type: string
          description: Human-readable error message
          example: "The provided credentials are incorrect"